export enum ComponentName {
  ACCORDION = 'ACCORDION',
  ACCORDION_SECTION = 'ACCORDION_SECTION',
  ACCORDION_SECTION_HEADER = 'ACCORDION_SECTION_HEADER',
  ACCORDION_SECTION_PANEL = 'ACCORDION_SECTION_PANEL',
  ALERT = 'ALERT',
  ALERT_DIALOG = 'ALERT_DIALOG',
  ALERT_DIALOG_ACTIONS = 'ALERT_DIALOG_ACTIONS',
  ALERT_DIALOG_DESCRIPTION = 'ALERT_DIALOG_DESCRIPTION',
  ALERT_DIALOG_TITLE = 'ALERT_DIALOG_TITLE',
  BREADCRUMB = 'BREADCRUMB',
  BREADCRUMB_LIST = 'BREADCRUMB_LIST',
  BREADCRUMB_LIST_ITEM = 'BREADCRUMB_LIST_ITEM',
  BREADCRUMB_LIST_ITEM_LINK = 'BREADCRUMB_LIST_ITEM_LINK',
  FOCUS_TRAP = 'FOCUS_TRAP'
}

export enum LoggerLevel {
  DEBUG = 0,
  INFO = 1,
  WARN = 2,
  ERROR = 3
}

export enum Key {
  ARROW_DOWN = 'ArrowDown',
  ARROW_UP = 'ArrowUp',
  END = 'End',
  ENTER = 'Enter',
  ESCAPE = 'Escape',
  HOME = 'Home',
  SPACE = ' ',
  TAB = 'Tab'
}
